### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by fhocorp** [c0d3z3r0/rbmode#2]
Help Needed. The tool is not working on my Riverbed Steelhaed 1050 

`rbmode u
Setting mode to universal
Traceback (most recent call last):
  File "/usr/local/sbin/rbmode", line 78, in <module>
    main()
  File "/usr/local/sbin/rbmode", line 70, in main
    setMode(args.mode)
  File "/usr/local/sbin/rbmode", line 38, in setMode
    s = smbus.SMBus(0)
IOError: [Errno 2] No such file or directory
`

**Comment by paalgyula** [comment]
modprobe i2c-dev
